baseURL = "https://flexitefire.no"
languageCode = "en-us"
title = "Flexite Fire AS"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "Flexite Fire fire-department administration tool"

[Author]
    name = "Roy Dybing"
    email = "roy@flexitefire.no"

[Social]
    twitter = "DybingRoy"
